### ISSUE TITLE
Version number in tags

### ISSUE THREAD

**Issue by njh** [netpieio/microgear-esp8266-arduino#11]
Hello,

I am the maintainer the the ArduinoLibraries.info website:
http://www.arduinolibraries.info/libraries/esp8266-microgear

My script has been having trouble finding the version tags for your library because the tag names are prefixed with 'v.'

Do you mind renaming them to plain '1.2.1'?

Thanks!

nick.

**Comment by chavee** [comment]
Hello Nick,

Thank you very much for letting me know. But I see that the lastest version 1.2.2 is now up in the arduino IDE library manager. But I have not changed anything yet. Do I still need to rename the release tag from v1.2.2 to 1.2.2 ? 

Thank you
Chavee

**Comment by njh** [comment]
You don't need to for the Arduino IDE library manager to work - it just seems to scan all the tags and extracts the version number from each of them.

But it makes it much easier for others to find the tag/history of a version, if the version number in library.properties matches the tag name.

**Comment by njh** [comment]
Thanks for creating [v1.2.2](https://github.com/netpieio/microgear-esp8266-arduino/commits/v1.2.2).
